services:
   mongo:
     image: mongo:6
     container_name: mongo_rs
     restart: always
     command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
     ports:
       - "27017:27017"
     volumes:
       - mongo_data:/data/db
 
   mongo-init:
     image: mongo:6
     container_name: mongo_init
     restart: "no"
     depends_on:
       - mongo
     entrypoint: [ "sh", "-c", "sleep 5 && mongosh --host mongo:27017 --eval 'rs.initiate({_id:\"rs0\", members:[{_id:0, host:\"mongo:27017\"}]})'" ]
 
volumes:
   mongo_data: