services:
  mongo:
    image: mongo:6
    container_name: mongo_rs
    restart: always
    command: ["sh", "-c", "mongod --replSet rs0 --bind_ip_all & sleep 5 && mongosh --host localhost:27017 --eval 'rs.initiate({_id:\"rs0\", members:[{_id:0, host:\"localhost:27017\"}]})'"]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
