services:
  react-app:
    build:
      context: .
      target: ${BUILD_TARGET:-development}
    ports:
      - "${PORT:-5173}:${PORT:-5173}"
    volumes:
      - .:/app
      - /app/node_modules  
    environment: 
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
