version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "3000:3000"

  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    volumes:
      - influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana:/var/lib/grafana 

volumes:
  influxdb:
  grafana:

# Windows Powershell

# $influxdbId = docker-compose ps -q influxdb

# docker run --rm -i `
#   --network container:$influxdbId `
#   -v "${PWD}:/scripts" `
#   grafana/k6 run /scripts/k6/test.js `
#   --out influxdb=http://influxdb:8086/k6
