services:
  api:
    build: ./api
    ports:
      - "3000:3000"

  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    volumes:
      - influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana:/var/lib/grafana

  k6:
    image: grafana/k6
    volumes:
      - ./k6:/scripts
    entrypoint: [""]
    command: >
      sh -c "k6 run /scripts/test.js --out influxdb=http://influxdb:8086/k6"
    depends_on:
      - api
      - influxdb

volumes:
  influxdb:
  grafana:
