services:
  app:
    container_name: node-ts-app
    build:
      context: .
      target: "${BUILD_TARGET:-development}"
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules   
